-- SQLite INSERT statements for ticket_entry table
-- Generated: 2025-11-14T07:44:36.457Z
-- Ticket range: 1866 to 1875
-- Event ID: 1
-- Secret: Mnep***
-- Note: Uses INSERT OR REPLACE to handle existing tickets

BEGIN TRANSACTION;

INSERT OR REPLACE INTO ticket_entry (id, event_id, token, created_at, entered_at, entered_by, attendee_name, attendee_phone, metadata_updated_at) VALUES (1866, 1, 'AJZi7L', COALESCE((SELECT created_at FROM ticket_entry WHERE id = 1866 AND event_id = 1), datetime('now')), (SELECT entered_at FROM ticket_entry WHERE id = 1866 AND event_id = 1), (SELECT entered_by FROM ticket_entry WHERE id = 1866 AND event_id = 1), (SELECT attendee_name FROM ticket_entry WHERE id = 1866 AND event_id = 1), (SELECT attendee_phone FROM ticket_entry WHERE id = 1866 AND event_id = 1), (SELECT metadata_updated_at FROM ticket_entry WHERE id = 1866 AND event_id = 1));
INSERT OR REPLACE INTO ticket_entry (id, event_id, token, created_at, entered_at, entered_by, attendee_name, attendee_phone, metadata_updated_at) VALUES (1867, 1, '6PXiWR', COALESCE((SELECT created_at FROM ticket_entry WHERE id = 1867 AND event_id = 1), datetime('now')), (SELECT entered_at FROM ticket_entry WHERE id = 1867 AND event_id = 1), (SELECT entered_by FROM ticket_entry WHERE id = 1867 AND event_id = 1), (SELECT attendee_name FROM ticket_entry WHERE id = 1867 AND event_id = 1), (SELECT attendee_phone FROM ticket_entry WHERE id = 1867 AND event_id = 1), (SELECT metadata_updated_at FROM ticket_entry WHERE id = 1867 AND event_id = 1));
INSERT OR REPLACE INTO ticket_entry (id, event_id, token, created_at, entered_at, entered_by, attendee_name, attendee_phone, metadata_updated_at) VALUES (1868, 1, '6GmiNr', COALESCE((SELECT created_at FROM ticket_entry WHERE id = 1868 AND event_id = 1), datetime('now')), (SELECT entered_at FROM ticket_entry WHERE id = 1868 AND event_id = 1), (SELECT entered_by FROM ticket_entry WHERE id = 1868 AND event_id = 1), (SELECT attendee_name FROM ticket_entry WHERE id = 1868 AND event_id = 1), (SELECT attendee_phone FROM ticket_entry WHERE id = 1868 AND event_id = 1), (SELECT metadata_updated_at FROM ticket_entry WHERE id = 1868 AND event_id = 1));
INSERT OR REPLACE INTO ticket_entry (id, event_id, token, created_at, entered_at, entered_by, attendee_name, attendee_phone, metadata_updated_at) VALUES (1869, 1, '6blil7', COALESCE((SELECT created_at FROM ticket_entry WHERE id = 1869 AND event_id = 1), datetime('now')), (SELECT entered_at FROM ticket_entry WHERE id = 1869 AND event_id = 1), (SELECT entered_by FROM ticket_entry WHERE id = 1869 AND event_id = 1), (SELECT attendee_name FROM ticket_entry WHERE id = 1869 AND event_id = 1), (SELECT attendee_phone FROM ticket_entry WHERE id = 1869 AND event_id = 1), (SELECT metadata_updated_at FROM ticket_entry WHERE id = 1869 AND event_id = 1));
INSERT OR REPLACE INTO ticket_entry (id, event_id, token, created_at, entered_at, entered_by, attendee_name, attendee_phone, metadata_updated_at) VALUES (1870, 1, 'qoLiPZ', COALESCE((SELECT created_at FROM ticket_entry WHERE id = 1870 AND event_id = 1), datetime('now')), (SELECT entered_at FROM ticket_entry WHERE id = 1870 AND event_id = 1), (SELECT entered_by FROM ticket_entry WHERE id = 1870 AND event_id = 1), (SELECT attendee_name FROM ticket_entry WHERE id = 1870 AND event_id = 1), (SELECT attendee_phone FROM ticket_entry WHERE id = 1870 AND event_id = 1), (SELECT metadata_updated_at FROM ticket_entry WHERE id = 1870 AND event_id = 1));
INSERT OR REPLACE INTO ticket_entry (id, event_id, token, created_at, entered_at, entered_by, attendee_name, attendee_phone, metadata_updated_at) VALUES (1871, 1, 'qRKi4w', COALESCE((SELECT created_at FROM ticket_entry WHERE id = 1871 AND event_id = 1), datetime('now')), (SELECT entered_at FROM ticket_entry WHERE id = 1871 AND event_id = 1), (SELECT entered_by FROM ticket_entry WHERE id = 1871 AND event_id = 1), (SELECT attendee_name FROM ticket_entry WHERE id = 1871 AND event_id = 1), (SELECT attendee_phone FROM ticket_entry WHERE id = 1871 AND event_id = 1), (SELECT metadata_updated_at FROM ticket_entry WHERE id = 1871 AND event_id = 1));
INSERT OR REPLACE INTO ticket_entry (id, event_id, token, created_at, entered_at, entered_by, attendee_name, attendee_phone, metadata_updated_at) VALUES (1872, 1, 'VnlivQ', COALESCE((SELECT created_at FROM ticket_entry WHERE id = 1872 AND event_id = 1), datetime('now')), (SELECT entered_at FROM ticket_entry WHERE id = 1872 AND event_id = 1), (SELECT entered_by FROM ticket_entry WHERE id = 1872 AND event_id = 1), (SELECT attendee_name FROM ticket_entry WHERE id = 1872 AND event_id = 1), (SELECT attendee_phone FROM ticket_entry WHERE id = 1872 AND event_id = 1), (SELECT metadata_updated_at FROM ticket_entry WHERE id = 1872 AND event_id = 1));
INSERT OR REPLACE INTO ticket_entry (id, event_id, token, created_at, entered_at, entered_by, attendee_name, attendee_phone, metadata_updated_at) VALUES (1873, 1, 'VyZioN', COALESCE((SELECT created_at FROM ticket_entry WHERE id = 1873 AND event_id = 1), datetime('now')), (SELECT entered_at FROM ticket_entry WHERE id = 1873 AND event_id = 1), (SELECT entered_by FROM ticket_entry WHERE id = 1873 AND event_id = 1), (SELECT attendee_name FROM ticket_entry WHERE id = 1873 AND event_id = 1), (SELECT attendee_phone FROM ticket_entry WHERE id = 1873 AND event_id = 1), (SELECT metadata_updated_at FROM ticket_entry WHERE id = 1873 AND event_id = 1));
INSERT OR REPLACE INTO ticket_entry (id, event_id, token, created_at, entered_at, entered_by, attendee_name, attendee_phone, metadata_updated_at) VALUES (1874, 1, 'VdgiX0', COALESCE((SELECT created_at FROM ticket_entry WHERE id = 1874 AND event_id = 1), datetime('now')), (SELECT entered_at FROM ticket_entry WHERE id = 1874 AND event_id = 1), (SELECT entered_by FROM ticket_entry WHERE id = 1874 AND event_id = 1), (SELECT attendee_name FROM ticket_entry WHERE id = 1874 AND event_id = 1), (SELECT attendee_phone FROM ticket_entry WHERE id = 1874 AND event_id = 1), (SELECT metadata_updated_at FROM ticket_entry WHERE id = 1874 AND event_id = 1));
INSERT OR REPLACE INTO ticket_entry (id, event_id, token, created_at, entered_at, entered_by, attendee_name, attendee_phone, metadata_updated_at) VALUES (1875, 1, 'qvviWY', COALESCE((SELECT created_at FROM ticket_entry WHERE id = 1875 AND event_id = 1), datetime('now')), (SELECT entered_at FROM ticket_entry WHERE id = 1875 AND event_id = 1), (SELECT entered_by FROM ticket_entry WHERE id = 1875 AND event_id = 1), (SELECT attendee_name FROM ticket_entry WHERE id = 1875 AND event_id = 1), (SELECT attendee_phone FROM ticket_entry WHERE id = 1875 AND event_id = 1), (SELECT metadata_updated_at FROM ticket_entry WHERE id = 1875 AND event_id = 1));

COMMIT;

-- Total tickets processed: 10
-- Existing tickets will have their tokens updated while preserving entry data